.MODEL SMALL
.STACK;PILA
CR EQU 13 ;RETORNO DE CARRO DEFINIDO EN UNA VARIABLE QUE ES CR CON SU VALOR DECIMAL DE LA TABLA ASCII 10
LF EQU 10 ;SALTO DE LINEA DEFINIDO EN UNA VARIABLE QUE ES LF CON SU VALOR DECIMAL DE LA TABLA ASCII 13
HT EQU 09 ;TABULACION HORIZONTAL.
.DATA;DATOS DEL PROGRAMA
CADENA0 DB LF,CR,HT,HT,HT,'PROGRAMA 1','$',,0dh,0ah
CADENA1 DB LF,CR,'MI NOMBBRE ES:',82,79,71,69,76,73,79,32,77,79,78,82,79,89,32,77,65,76,68,79,78,65,68,79,'$',0dh,0ah;CONCATENAMIENTO DE MI NOMBRE CON VALORES DE LA TABLA ASCII
CADENA2 DB LF,CR,'LUGAR DONDE NACI:',67,73,85,68,65,68,32,68,69,32,77,69,88,73,67,79,'$',0dh,0ah ;CONCATENAMIENTO DE MI LUGAR DE NACIEMINETO
CADENA3 DB LF,CR,'MI PASATIEMPO:',86,69,82,32,86,73,68,69,79,83,'$',0dh,0ah;CONCATENAMINETO DE UN PASATIEMPO
.CODE ;CODIGO DEL PROGRAMA
PROGRAMA:;NOMBRE DEL PROGRAMA 
    MOV AX,@DATA;MOVEMOS EL SEGMENTO DE DATOS A AX=ACOMULADOR
    MOV DS,AX;MOVEMOS AX A DS=RESGISTRO DE SEGMENTO DE DATOS 
    MOV DX,OFFSET CADENA0	    ;MOVEMOS  AL DX=REGISTRO DE DATOS LA CADENA0 EN UNA POSICION SUMADAS DE UNA DIRECCION BASE EN TERMINOS GENERALES LE DA UNA POSICION NUEVA
    MOV AH,09h					;POCION DEL CURSOR PARA VISUALIZAR LA CADENA DE CARACTERES
    INT 21H 					;INTERRUPCION DE INVOCACION DE SERVICIOS DEL DOS
    MOV DX,OFFSET CADENA1      
    MOV AH,09h                
    INT 21H                    
    MOV DX,OFFSET CADENA2
    MOV AH,09h
    INT 21H 
    MOV DX,OFFSET CADENA3
    MOV AH,09h
    INT 21H 
    MOV AH,4Ch                  ;FUNCION DE TERMINACION DE PROGRAMA
    INT 21H 					;LLAMADA DE LA FUSION DE INTERRRUPCION
END PROGRAMA;FIN DEL PROGRAMA
END
