MODEL SMALL
.STACK 
CR EQU 13 ;RETORNO DE CARRO DEFINIDO EN UNA VARIABLE QUE ES CR CON SU VALOR DECIMAL DE LA TABLA ASCII 10
LF EQU 10 ;SALTO DE LINEA DEFINIDO EN UNA VARIABLE QUE ES LF CON SU VALOR DECIMAL DE LA TABLA ASCII 13
HT EQU 09 ;TABULACION HORIZONTAL.
.DATA
    CADENA0  DB  LF,CR,HT,HT,HT,'PROGRAMA 3$',0dh,0ah
    LEER     DB  LF,CR,'Ingrese un caracter: $'
    ESCRIBIR   DB  LF,CR,'El caracter que ingresaste es: $'   
        
.CODE
    inicio: 
        mov ax, @Data ;MOVEMOS LOS DATOS A AX=ACOMULADOR
        mov ds, ax ;MOVEMOS AX A DS=RESGISTRO DE SEGMENTO DE DATOS 
        
        mov ah, 09h;;POCION DEL CURSOR PARA VISUALIZAR LA CADENA DE CARACTERES
        mov dx, offset CADENA0 ;MOVEMOS  AL DX=REGISTRO DE DATOS LA DESCRIPCION A UNA NUEVA POSICION
        int 21h;LLAMAMOS AL SISTEMA
        
        mov ah, 09h ;POCION DEL CURSOR PARA VISUALIZAR LA CADENA DE CARACTERES
        mov dx, offset LEER ;MOVEMOS  AL DX=REGISTRO DE DATOS LA DESCRIPCION A UNA NUEVA POSICION
        int 21h;LLAMADA AL SISTEMA

        mov ah, 01 ;ENTRADA DE CARACTER 
        int 21h ;LLAMADA AL SISTEMA
        
        mov cl, al ; MOVEMOS AL A CL
        
        mov ah, 09h;POSICION DEL CURSOR VISUALIZAR LA CADENA DE CARACTERES
        mov dx, offset ESCRIBIR ;MOVEMOS  AL DX=REGISTRO DE DATOS LA DESCRIPCION A UNA NUEVA POSICION
        int 21h ;LLAMADA AL SISTEMA
        
        mov ah, 02 ;IMPRECION DEL CARACTER LEIDO EN EL REGSITRO AH
        mov dl, cl;MOVER DATOS DE LOS REGISTROS BASJOS DE CX Y DX
        int 21h;LLAMADA AL SISTEMA
        
        mov ax, 4c00h
        int 21h
    END inicio
