.MODEL SMALL
.STACK;PILA
CR EQU 13 ;RETORNO DE CARRO DEFINIDO EN UNA VARIABLE QUE ES CR CON SU VALOR DECIMAL DE LA TABLA ASCII 10
LF EQU 10 ;SALTO DE LINEA DEFINIDO EN UNA VARIABLE QUE ES LF CON SU VALOR DECIMAL DE LA TABLA ASCII 13
HT EQU 09 ;TABULACION HORIZONTAL.
.DATA;DATOS DEL PROGRAMA
CADENA0 DB LF,CR,HT,HT,HT,'PROGRAMA 2$',0dh,0ah
CADENA1 DB LF,CR,'EL UNICO MODO DE HACER UN GRAN TRABAJO ES AMAR LO QUE HACES.....$',0dh,0ah 

.CODE ;CODIGO DEL PROGRAMA
PROGRAMA:;NOMBRE DEL RPOGRAMA
    MOV AH,02;Iniciamos la funcion de posicionamineto de cursor
    MOV DL,0000H; Asignacion de la posicion del cursor en la linea 0
    INT 10H;Llamada de la interrupsion
    MOV AX,06H;Iniar fucnicon delplazamiento de lineas de texto hacia arriba
    MOV BH,07H;Llamamos a una suncion de desplazamineto de lineas de texto hacia arriba
    MOV CX,0000H;Limitamos el pocicionamiento del desplazamiento desde la linea 0 hata
    MOV DX,194FH;La linea 6479 que seria el limite de nuestra pantalla;
    INT 10H;Llamamos a la interrupcion
    MOV AX,@DATA;MOVEMOS EL SEGMENTO DE DATOS A AX=ACOMULADOR
    MOV DS,AX;MOVEMOS AX A DS=RESGISTRO DE SEGMENTO DE DATOS
    MOV DX,OFFSET CADENA0;MOVEMOS  AL DX=REGISTRO DE DATOS LA CADENA1 EN UNA POSICION SUMADAS DE UNA DIRECCION BASE EN TERMINOS GENERALES LE DA UNA POSICION NUEVA
    MOV AH,09h;POCION DEL CURSOR PARA VISUALIZAR LA CADENA DE CARACTERES
    INT 21H ; 
    MOV DX,OFFSET CADENA1;MOVEMOS  AL DX=REGISTRO DE DATOS LA CADENA1 EN UNA POSICION SUMADAS DE UNA DIRECCION BASE EN TERMINOS GENERALES LE DA UNA POSICION NUEVA
    MOV AH,09h;POCION DEL CURSOR PARA VISUALIZAR LA CADENA DE CARACTERES
    INT 21H ;INTERRUPCION DE INVOCACION DE SERVICIOS DEL DOS
    MOV AH,4Ch ;Funcion terminar programa
    INT 21H    ;Llamada de la funcion
END PROGRAMA;FIN DEL PROGRAMA
END

